name: .NET Core

on:
  push:
    branches: [ master ]

jobs:
  publish:
    name: list on nuget
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.301
    - name: Build with dotnet
      run: dotnet build src --configuration Release
    - name: Test
      run: dotnet test src
    - name: Publish RandomCoffee.Yammer on version change
      uses: brandedoutcast/publish-nuget@v2.5.3
      with:
        PROJECT_FILE_PATH: src/RandomCoffee.Yammer/RandomCoffee.Yammer.csproj
        TAG_COMMIT: false
        VERSION_REGEX: <Version>(.*)<\/Version>
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

